### PR TITLE
Add support for Idea build 201

### PR DESCRIPTION
**Pull request by roelvs**

### CODE REVIEW

**Comment by prowave** [comment]
+1

image

**Comment by leomelin** [comment]
Merge please...

**Comment by fabianocruzdf** [comment]
MERGE PLEASE!!!!!

**Comment by serkanayaz** [comment]
@OpherV Merge Please...

**Comment by tumb1er** [comment]
@OpherV Merge Please...

**Comment by OpherV** [comment]
This PR does nothing. Changing a string in the manifest isn't enough. It doesn't address **actual support** for the build, it just lets the IDE "know" it can attempt to install and run the plugin, which obviously would print errors in the good case and break something with your repo in the bad case. 

If you want to contribute actual support for the 2020 build, you can address these support and deprecation issues from the IDEA platform, build and test test test. 

image

I spend a lot of time each version to make sure everything is working safely.

Copy pasting "Merge please" in upper case isn't helpful, meaningful commits are.
These are trying times, you will just have to be patient, use the previous version of IDEA for the time being, or do the actual work yourself.

**Comment by tumb1er** [comment]
Wow, this info should be present in README. Most of community know nothing about actual API compatibility state, that is why these PRs and comments are present.

**Comment by mfu-aroche** [comment]
While @OpherV is checking for compatibility issues with the new API, if you really want to use this plugin, here is a workaroud.

1. Go to `JetBrains/PhpStorm2020.1/plugins/gitflow4idea/libl` (see https://www.jetbrains.com/help/idea/tuning-the-ide.html#default-dirs to find the config directory on your OS).
2. Open `gitflow4idea-0.7.1.jar` with something that allow you to edit files within (on Windows you can use 7zip).
3. Open file `META-INF/plugin.xml`.
4. Replace line `<idea-version since-build="182.0" until-build="193.*"/>` by `<idea-version since-build="182.0" until-build="201.*"/>` and save file.
5. If `gitflow4idea-0.7.1.jar` was correctly modified, just restart PhpStorm or whatever JetBrains IDE you're using and enjoy.

While I would recommend to wait for a proper fix, this workaround worked for me without having any error.

**Comment by wxy8866** [comment]
No Push. wait for @OpherV to finish the platform level API upgrade.

**Comment by OpherV** [comment]
Thanks to excellent work by @tumb1er and @fabmars we now have proper support. Closing this as soon as the new version goes up

**Comment by OpherV** [comment]
0.7.2 now out

**Pull request closed without merging**
