### PR TITLE
IDEA 2019.2 (build 192.*)

### PR DESCRIPTION
**Pull request by edimarlnx**

### CODE REVIEW

**Comment by edimarlnx** [comment]
Issue: #241

**Comment by lancedikson** [comment]
@OpherV, could you, please, take a look at this one? We're missing gitflow on the latest WS version  😸

**Comment by Josemino** [comment]
@OpherV Please, when will it be available for version 2019.2?

**Comment by bbakermmc** [comment]
@OpherV Guess hes abandoned the project.  Seems to take months to get new versions, wish someone else would take over the project.

**Comment by lancedikson** [comment]
I've contacted Opher yesterday and he promised to release an update soon: https://twitter.com/Opherv/status/1161630554766348288

**Comment by OpherV** [comment]
@bbakermmc 
I haven't abandoned the project and a new version will be released probably next week.

I apologize if this free software that you're getting for free doesn't meet your expectations. By 'someone else' are you volunteering yourself? Because in the 6 years I've been maintaining and supporting this project on my own dime I haven't received one pull request or support from you. I'm grateful for every contribution other people have made over the years be it by code, writing docs, testing, offering support to other users or just putting in a good word.

You have done neither of those. If you have an idea of someone else who'll be willing to magically work for free for the long run by all means please bring them forward.

**Comment by OpherV** [comment]
Btw this PR is superficial and doesn't address the issue of actions running as synchronous execution on EDT, which I'm working to sort out before we have true 2019.2 support

**Comment by lancedikson** [comment]
Thanks for the update! I'd love to help, but I know Java on a really basic level.

**Comment by OpherV** [comment]
Version 0.6.9 is out on the Jetbrains repo

**Comment by lancedikson** [comment]
Thank you very much! 🙏

**Pull request closed without merging**
