### PR TITLE
Added 'pushOnFinish' as it got added to gitflow itself as well (…

### PR DESCRIPTION
**Pull request by bmwsedee**
As mentioned in https://github.com/OpherV/gitflow4idea/issues/99, when 'push on finish feature' would be implemented by gitflow AVH edition, it could also be implemented in the plugin, so that's why I hope to have done here (as it got implemented by https://github.com/petervanderdoes/gitflow-avh/issues/261)

### CODE REVIEW

**Comment by OpherV** [comment]
Thanks for this! FYI I'm waiting until we merge #208 to merge this (because file locations might change)

**Comment by OpherV** [comment]
#208 was merged, can you please update your PR? Thanks :)

**Comment by bmwsedee** [comment]
Should be fixed :)

**Comment by OpherV** [comment]
Merged! Thanks

**Pull request merged**
