### PR TITLE
Support for 2020.3 build

### PR DESCRIPTION
**Pull request by tschmidt01**

### CODE REVIEW

**Review by banagale — APPROVED** [review]

**Comment by banagale** [comment]
I've run this PR using the [Gradle Setup](https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md) and validated it runs as expected.

Only item I noticed is a known exception due #314.

**Comment by GaLaKtIkUs** [comment]
Hi, any updates on this issue?

**Comment by sercheo87** [comment]
@OpherV  Do you have an update date for this plugin or will you already release a new version?

**Comment by applibs** [comment]
Can you change untilBuild '203.*' to untilBuild '300.*' for example? Otherwise you have to changing this always when IJ is updated. With 255.* will be always working and users using this plugin will be always happy.
Ofcource that when something in IJ will be changed and plugin will stop work but its less chance.

**Comment by tumb1er** [comment]
JetBrains breaks and deprecates Idea internals in 20x builds, so you'll install a non-working plugin version. If you wish you can fork, build and install local version.

**Comment by banagale** [comment]
I was able to build using the docs, but was unclear on how to get at and
install the local version in pycharm. Would you mind briefly explaining
that process?

**Comment by tumb1er** [comment]
> unclear on how to get at and install the local version in pycharm

1. Open action search popup ("Ctrl + Shift + A") and search "Install plugin from Disk..."
2. Locate `build/libs/gitflow4idea-x.y.z.jar` under Idea project dir 
3. Restart PyCharm

Installed plugin in list

**Comment by tumb1er** [comment]
#314 is fixed in #317

@OpherV is there anything else that community can help with to publish 2020.3 family support?

**Comment by OpherV** [comment]
@tumb1er 
Thanks for the offer. A new version is planned to go live on the jebrains repo later this week

**Comment by OpherV** [comment]
0.7.5 is out with 2020.3 support

**Pull request closed without merging**
