### PR TITLE
Gradle setup

### PR DESCRIPTION
**Pull request by straurob**
While setting up the project for development I noticed that the setup includes a number of manual steps and settings. This could increase the risk for errors and unnecessary troubleshooting. As I also fell into some traps my motivation was to automate some of these setup tasks with Gradle - which is also the preferred way recommended by JetBrains.

This PR provides a basic setup with Gradle for further evaluation and maybe it's useful for the project.

### CODE REVIEW

**Comment by OpherV** [comment]
Wow!

I must admit I've never worked with Gradle (I'm mainly a web dev and not a Java dev) - but it seems a very interesting direction

I have a few question I hope you can answer:
- What are the benefits of building with Gradle?
- Can we use Gradle to do automated GUI testing (#205)? If so that would be amazing! 
- Why is it necessary to change the file structure from `src/main/gitlfow` to `src/main/java/gitflow`?

**Comment by straurob** [comment]
Thank you. As I'm also a novice using Gradle I'll try my best to answer your questions...

> What are the benefits of building with Gradle?

I would say the main benefit is the ability to automate tasks from the perspective of _building the project_.

Example:
You have defined the following in the `build.gradle` file.
```
intellij {
    version '2018.2.1'
    plugins 'git4idea', 'tasks'
}
```
Gradle will take care about downloading this exact version of IntelliJ and the corresponding plugins. You don't need to manually download releases, set paths which could differ from machine to machine, etc.

> Can we use Gradle to do automated GUI testing?

Gradle itself cannot be used for UI automation but it could trigger/handle it once some automated checks are implemented. I'm also checking the testing guides from Jet

> Why is it necessary to change the file structure?

I'm not sure if it is actually _necessary_ to change the structure. However it is the default used by Gradle Java projects.

Please see this link for more details:
https://docs.gradle.org/current/userguide/organizing_gradle_projects.html

**Comment by OpherV** [comment]
@straurobNote that since I've merged the bugfix feature PR this PR can't be merged - address this and I'll merge this too, then I'll release a new version of the plugin to the jetbrains repo

**Comment by OpherV** [comment]
I apologize for the delay - looks like there's one more thing to handle before the merge, that is that the BugFix files are in `src/gitflow` and the rest are in `main/java.gitflow/`
We need to be consistent with one or the other :)
image

**Comment by straurob** [comment]
Glad youd found this inconsistency. I corrected the structure so that all sources reside in the java directory.

**Comment by straurob** [comment]
Hi @OpherV, Is there any update on this pull request? Or are you busy? In the latter case, please excuse me :-)

**Comment by OpherV** [comment]
Merged. Again sorry for the delay, I have a 3 month old baby which takes up pretty much all of my free time recently!

I have some more incoming PRs to review, then I'll upload a new version to the intellij repo so all of your hard work will finally be out :)

**Comment by straurob** [comment]
Sorry... I forgot about that but will remember in the future. Your baby is way more important than this :-) A very Merry Christmas to you and your family.

**Pull request merged**
