### PR TITLE
don't cache status bar widget in factory

### LINKED ISSUE #301: Version 0.7.2 causes that Active Tool Windows only is showed in one project if you have several open
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Active Tool Windows only is showed in one project if you have several open.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Open one project (this has active tool window)
3. Open several more projects in a new window (this hasn't active tool windows)

* **What is the expected behavior?**
Every project window have to available active tool window.

* **What is the motivation / use case for changing the behavior?**
This bug only happen with this plugin enabled.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *find in IntelliJ settings plugins* -> 0.7.2
  - Gitflow version: run in terminal `>git flow version` -> 1.12.0 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*

> IntelliJ IDEA 2020.1.1 (Ultimate Edition)
> Build #IU-201.7223.91, built on April 30, 2020
> Runtime version: 11.0.6+8-b765.40 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1933M
> Cores: 8
> Non-Bundled Plugins: CMD Support, org.jetbrains.plugins.hocon, mobi.hsz.idea.gitignore, io.protostuff.protostuff-jetbrains-plugin, net.seesharpsoft.intellij.plugins.csv, org.intellij.scala, com.intellij.bigdatatools, Pythonid

### PR DESCRIPTION
**Pull request by tumb1er**
closes #301
cached widget could not be added to second project window, ide crashed

### CODE REVIEW

**Comment by OpherV** [comment]
@tumb1er I feel like this would lead to a memory leak.
The proper way to go about it is do caching per project - create a map object with projects as keys and widgets as values. Want to try and give it a go?

**Comment by tumb1er** [comment]
I'll try it.

**Comment by tumb1er** [comment]
@OpherV I looked through internal Idea factories and didn't find any factory that uses widget caching. Every factory calls `Disposer.dispose(widget)` like this ont, so memory leak is unlikely.

**Comment by tumb1er** [comment]
The only factory with caching is StatusBarWidgetProviderToFactoryAdapter, but 1) it is marked internal 2) it is obviously compatibility support code

**Comment by OpherV** [comment]
Ok, fair enough. Merged

**Pull request merged**
