### PR TITLE
include builds up to 163.*

### PR DESCRIPTION
**Pull request by ctaepper**
so it works in Webstorm 2016.3

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Awesome!

**Comment by OpherV** [comment]
Cool. Did you test this thoroughly?

**Comment by ctaepper** [comment]
if by thoroughly you mean am I using this in my webstorm 2016.3 instance without any errors, then yes :)

**Comment by OpherV** [comment]
haha, sounds good :)

**Comment by ctaepper** [comment]
i'm no java developer, my knowledge stops right here at updating a version info, but as i said, everything seems to work fine

**Pull request merged**
